### ISSUE TITLE
Multilingual navbar

### ISSUE THREAD

**Issue by Guileas** [RatanShreshtha/DeepThought#11]
Thank you for your great work on DeepThought, I really like your theme and want to use it.
I would like to create a multilingual navbar based on what already exists do you have any idea how I can do that?

**Comment by RatanShreshtha** [comment]
@Guileas I have not looked in to multilingual sites yet but I think https://www.getzola.org/documentation/content/multilingual/ might be of help to you. If you are able to get the site up and running then may be you can raise a PR for that.

**Comment by Guileas** [comment]
@RatanShreshtha I've found a way to do it on my blog, I'm gonna make a PR
