### ISSUE TITLE
Dark theme inverts YouTube and Vimeo player colors.

### ISSUE THREAD

**Issue by IngrownMink4** [RatanShreshtha/DeepThought#14]
# Steps to reproduce:

- When you activate dark theme in your website and then you go to **https://deepthought-theme.netlify.app/docs/welcome-to-deep-thought/** if you reproduce the embedded videos (from YouTube and Vimeo), you can see that actually the colours are inverted.

# Expected results:

- The embedded videos shouldn't be affected by the dark theme. They shouldn't have inverted colours.

# Tested in:

* Firefox Nightly 88 and Firefox Stable 86 (I could reproduce it)
* Ungoogled Chromium 88 (I could reproduce it)

![firefox_lgnQebFATc](https://user-images.githubusercontent.com/25466522/109865123-fa6d3680-7c63-11eb-9340-bfe9d9318e67.png)

**Comment by RatanShreshtha** [comment]
I am going to fix this in next release meanwhile if you have a fix ready then you can raise a PR for that.

**Comment by RatanShreshtha** [comment]
@IngrownMink4 Fixed

**Comment by IngrownMink4** [comment]
> 
> 
> @IngrownMink4 Fixed

Hey @RatanShreshtha thanks for fixing that. Unfortunately in Firefox it seems that it's not fixed yet. In Chrome is working great tho (as you can see here)

Firefox
![firefox_AWCPamUFhn](https://user-images.githubusercontent.com/25466522/122089480-18bc0400-ce07-11eb-886d-6e6e36eab62c.png)

Chromium 
![chrome_RTGSI5GQJC](https://user-images.githubusercontent.com/25466522/122089486-19ed3100-ce07-11eb-84d3-71ba57b0c8b9.png)
