### ISSUE TITLE
Feature Proposal: optional JavaScript libraries 

### ISSUE THREAD

**Issue by martinmcwhorter** [RatanShreshtha/DeepThought#19]
I would like to make a pull request to make JavaScript libraries included a set of configuration options. 

Before I make the changes and submit a PR I would like to get your feedback on whether this is something that you will likely accept and which of these two implementation options I should choose.  

Within the site.js file there is some instantiation code for each library,  such as galleria. If galleria is not included this needs to be handled. 

We could:

1. Make the instantiation code checking check for the presence of the library
2. Or move the instantiation JavaScript into inline blocks in the base.html that can be conditionally included 

I would choose option 2.

option 1:

```javascript 
// site.js
if (Galleria) {
  $(".galleria").each(function (index) {
    $(this).attr("id", `galleria-${index}`);

    var { images } = JSON.parse($(this).text());

    for (let image of images) {
      $(this).append(
        `<a href="${image.src}"><img src="${image.src}" data-title="${image.title}" data-description="${image.description}"></a>`
      );
    }

    Galleria.run(`.galleria`);
  });
}
```

option 2:

```html 
// base.html
<script>
{% if config.extra.javascript.galleria %}
  $(".galleria").each(function (index) {
    $(this).attr("id", `galleria-${index}`);

    var { images } = JSON.parse($(this).text());

    for (let image of images) {
      $(this).append(
        `<a href="${image.src}"><img src="${image.src}" data-title="${image.title}" data-description="${image.description}"></a>`
      );
    }

    Galleria.run(`.galleria`);
  });
{% endif %}
// more conditional javascript initializers here... 
</script>

```

**Comment by kenohassler** [comment]
@martinmcwhorter I share your opinion on the JavaScript libraries and made some changes in [my fork](https://github.com/kenohassler/DeepThought/tree/optional-libs).
I chose option 1 simply because it was less of a change – but I'm not committed on this. Furthermore I replaced the JQuery code in `site.js` with vanilla JavaScript, making JQuery an optional dependency only needed for Galleria.js :tada:.
@RatanShreshtha if you're interested, I can send a PR :smiley:

**Comment by RatanShreshtha** [comment]
@kenohassler Send the PR

**Comment by martinmcwhorter** [comment]
I went with option 2, but kept these within the template of the website. The reason being less smaller response sizes.

Like @kenohassler , I eliminated jquery for all but Galleria. 

I added on a proper dark mode, not using CSS color inversion. 

If any of this is wanted, I can create a PRs.

**Comment by kenohassler** [comment]
Hey @martinmcwhorter ,

Sounds great! I also played around with a dark Bulma theme, we seem to have a similar taste :D
Go ahead, send your PRs

**Comment by quadratecode** [comment]
@martinmcwhorter would you still be willing to share your code on the dark mode improvements now that @kenohassler has kindly provided the JS update?

**Comment by martinmcwhorter** [comment]
I wanted to get this done sooner than later. I can work on this tomorrow,
separating it out from other changes.

Should I assume we don't want any node/npm dependencies? Or is that
something this project is ok with adding?

**Comment by quadratecode** [comment]
Great news! By all means there is no hurry; I just wanted to inquire given your previous comment about having added a dark mode without inversion.

Can't speak to the question about the dependencies, since @RatanShreshtha is the owner. I personally do not mind them.
