### ISSUE TITLE
Can't use DeepThought as a theme - doesn't render anything in content/

### ISSUE THREAD

**Issue by jdeibele** [RatanShreshtha/DeepThought#2]
First, I've looked and installed Zola themes and DeepThought looks great.   Thank you for sharing it.

I've installed DeepThought into ~/zola/themes, then changed config.toml  
`theme = "DeepThought"`

I added the extra configuration options needed.

The problem is, when I do "zola serve" I get a blank site.  

The first image is the home page.  ( http://127.0.0.1:1111/ )
<img width="887" alt="Screen Shot 2020-10-07 at 13 48 41" src="https://user-images.githubusercontent.com/264802/95386237-d7e91400-08a3-11eb-85dc-1c99bb153377.png">

The second image is the /posts link. ( http://127.0.0.1:1111/posts )
<img width="735" alt="Screen Shot 2020-10-07 at 13 46 57" src="https://user-images.githubusercontent.com/264802/95386124-aec88380-08a3-11eb-87b8-a55646f5a904.png">

If I go into themes/DeepThought and then do "zola serve" I get your sample site.

As I understand it, I should leave your theme alone so I can check out updates from GitHub.   I should not put my content in your directory.   I've tried both ~/zola/content
```
zola serve                   
Building site...
-> Creating 6 pages (0 orphan), 0 sections, and processing 0 images
Done in 37ms.
```
and ~/zola/content/posts 
```
zola serve                  
Building site...
-> Creating 6 pages (6 orphan), 0 sections, and processing 0 images
Done in 30ms.
```

So ~/zola/content seems better.

Am I doing something wrong?

**Comment by RatanShreshtha** [comment]
You need a file `content/_index.md` which contains content for your index page and for posts add a file `content/posts/_index.md`. You can use the `content` directory of DeepThought as reference.
