### ISSUE TITLE
Avatar variable is required for 404 template, but not for index template

### ISSUE THREAD

**Issue by TheGhostHuCodes** [RatanShreshtha/DeepThought#3]
Hi, thanks for your work on this great looking zola theme!

When I was setting up my blog without an avatar, I noticed that in the `index.html` template it is not required.
https://github.com/RatanShreshtha/DeepThought/blob/master/templates/index.html#L7-L11

But for the `404.html` template it is required, and this breaks the static site build.
https://github.com/RatanShreshtha/DeepThought/blob/master/templates/404.html#L8-L10

Should we surround the 404 avatar image with a

```
{% if config.extra.author.avatar %}
...
{% endif %}
```
block?

**Comment by RatanShreshtha** [comment]
Thanks @TheGhostHuCodes for making me aware of it.

**Comment by TheGhostHuCodes** [comment]
@RatanShreshtha, do you take PRs for this repo? If so I'd be happy to make this fix.

**Comment by RatanShreshtha** [comment]
I fixed it recently and in future feel free to open PR for improvements :thumbsup: . Let me also add contribution guide as well for the repo.

**Comment by TheGhostHuCodes** [comment]
Fixed in 46642aa
