### ISSUE TITLE
A lot of things don't work on me (new on Zola)

### ISSUE THREAD

**Issue by rempas** [RatanShreshtha/DeepThought#36]
Hello! Like I'm saying, I'm new to Zola and I really liked this theme and wanted to make my blog with it. Thank you for your amazing work!!!

I'm trying to get started, I have read the [zola overview](https://www.getzola.org/documentation/getting-started/overview/) till the point to get started with my new project and then the [installing theme](https://www.getzola.org/documentation/themes/installing-and-using-themes/) section to install the theme just like you said. I also added a variable to the `config.toml` file to set the theme to DeepThought. Now I'm going to tell you exactly the steps I followed and the results I had so you can help me.

**PROBLEM ONE**
After installing the theme, I added the following variable in my `config.toml` file: `theme = "DeepThought"` just like you are saying in the `README.md`. After that I'm getting the following error message:
```
Error: Failed to render section '/home/rempas/Projects/Programming/Web/myblog/content/_index.md'
Reason: Failed to render 'index.html' (error happened in a parent template)
Reason: Variable `config.extra.navbar_items` not found in context while rendering 'index.html'
```
To fix that, I tried to copy the `config.toml` which is inside the theme to my project root directory. Additionally I added the variable to change the theme and now it works. The thing is. Is this suppose to be the case? Should I get the theme config? I'm asking because you don't said that in the `README.md` neither it is mentioned in the zola docs

**PROBLEM TWO**
The content is not showing up. While the `templates` and `static` directories didn't had to get copied to my root project directory to make them work, the content does not show up. I suppose this how Zola treats that posts. So is it safe to delete the `content` directory from the root directory of the `DeepThought` theme and just add posts in mine?

**PROBLEM THREE**
The search doesn't work. Do you have any idea why this is happening? I suppose it's probably a js thing but I have no idea...

**Comment by joesan** [comment]
You are not alone. I have been facing the same problems. Somehow copying the theme as a whole project into the themes directory does not work or is some documentation missing that tells us how to configure this. 

Have a look at the issue that I raised here: https://github.com/getzola/zola/issues/1623

**Comment by rempas** [comment]
@joesan Hi and sorry for the late answer. So I added the navbar_items undert the `[extra]` block and now the config works. However, now when I'm trying to either copy or move the contents from inside the `DeepThought` directory to my project root directory, I'm getting the following error message:
```
Error: Failed to render page '/home/rempas/Projects/Programming/Web/myblog/content/posts/post-10.md'
Reason: Failed to render 'page.html'
Reason: Function call 'get_taxonomy_url' failed
Reason: `get_taxonomy_url` received an unknown taxonomy as kind: categories
```

What's the progress you have made? Did you had this error yet?

**Comment by joesan** [comment]
@rempas It is the same error that even I got stuck with. Not sure how to progress!

**Comment by rempas** [comment]
Understand, thanks a lot for your time!

**Comment by joesan** [comment]
Is there a resolution? How to fix this?

**Comment by rempas** [comment]
Oh, no there is not. At least I haven't found one yet. I would have let you know differently of course. The truth is that at this point, I can't wait until (and if they do at all cause I don't see it coming) the developers support us so probably I'll go back on Hugo. So same cause Zola seems awesome. I'll leave the issue open tho in case someone sees and fixes it in the future. Good luck!

**Comment by RatanShreshtha** [comment]
New version of Zola is breaking few things as configs are changed I am working on fixing these in https://github.com/RatanShreshtha/DeepThought/tree/new-zola-version branch but so far few things are still breaking.

**Comment by joesan** [comment]
@rempas Even I was considering using Hugo. Might give it a try as well.

**Comment by joesan** [comment]
@rempas Even I was considering using Hugo. Might give it a try as well.

**Comment by rempas** [comment]
> 
> 
> New version of Zola is breaking few things as configs are changed I am working on fixing these in https://github.com/RatanShreshtha/DeepThought/tree/new-zola-version branch but so far few things are still breaking.

Oh!!! That's a nice shift! So it's a Zola thing after all... Thanks a lot for your work! If that's the case then I'm sticking around!

**Comment by AlexMikhalev** [comment]
I switched from Hugo to zola - grass is not greener there :) and DeepThought theme has everything I need.

**Comment by joesan** [comment]
Any updates on this issue? If you could point out where to look and what needs to be fixed, I can give it a try.

**Comment by AlexMikhalev** [comment]
Works for me on 0.14 zola with deep thought theme as sub module. Be careful with config.toml - check out theme config and copy as needed.

**Comment by joesan** [comment]
@rempas Did it work out for you? I moved over my content to Hugo as I came across a theme that contained most of the features that I was in need of.

**Comment by rempas** [comment]
@joesan Didn't tried it to tell you the truth. I left everything since 3 months ago and I just happened that I came back searching for new static site generators and I found out about [plenti](https://github.com/plentico/plenti) and [verless](https://github.com/verless/verless) and they both seem great but I don't know which one to choose between them...

**Comment by AlexMikhalev** [comment]
This one.

**Comment by rempas** [comment]
@AlexMikhalev Does this go on me? lol

**Comment by RatanShreshtha** [comment]
Everything should works fine now
