### ISSUE TITLE
Footer block is gone

### ISSUE THREAD

**Issue by hadilq** [RatanShreshtha/DeepThought#39]
Hey @RatanShreshtha, thank you for your great work here. I really appreciate it and it's a while that I am using it in my blog! However, today I pulled the last changes of this theme, where I noticed the footer block is not where it was before! It removed in [this commit](https://github.com/RatanShreshtha/DeepThought/commit/44c25559a039e7a5d73cb578ee0639a4680ca79d#diff-690b81fad8df2a1f1ce37c846641d9247e3472d244f17039d2910a5ed0c98d5eL176-L206). 

```
Fix 404 page 
@@ -173,7 +165,6 @@
  {% block comment %}
  {% endblock %}

-  {% block footbar %}
  <footer class="footer py-4">
    <div class="content has-text-centered">
      <p>
@@ -203,7 +194,6 @@
```

Is it intended or a mistake?

**Comment by RatanShreshtha** [comment]
This is intended as the 404.html page is inheriting from base.html

**Comment by hadilq** [comment]
Thank you for your answer, but would you explain more? What will happen if someone change the footer in 404 page?

**Comment by SkypLabs** [comment]
Hi @RatanShreshtha,

I don't see the link between the footer block and the 404 page either.

Could you please elaborate more on this?

Thanks.

**Comment by SkypLabs** [comment]
@hadilq Footer block is back! https://github.com/RatanShreshtha/DeepThought/pull/67
