### ISSUE TITLE
Lang variable

### ISSUE THREAD

**Issue by tchartron** [RatanShreshtha/DeepThought#42]
Hi,

I'm trying to learn Zola and i'm inspired by this great theme,
I'm sorry to post this as a github issue but i can't find where is the lang variable defined, could anyone help me ?

Thanks for helping and for sharing this great theme.

**Comment by RatanShreshtha** [comment]
https://github.com/RatanShreshtha/DeepThought/blob/1e8cb13c6994c3e15898b89fbbb9e7e133ecddd8/config.toml#L142

**Comment by tchartron** [comment]
Thanks but i don't see any `lang` variable definition here to be used in `templates/base.html` like it is here https://github.com/RatanShreshtha/DeepThought/blob/1e8cb13c6994c3e15898b89fbbb9e7e133ecddd8/templates/base.html#L4

**Comment by tchartron** [comment]
For anyone looking for this like i was here is the answer : https://www.getzola.org/documentation/templates/pages-sections/

`lang` variable is coming from Pages variables of Zola and defaults to config.toml default_language variable.
