### ISSUE TITLE
Please add Matodon to extra.social links

### ISSUE THREAD

**Issue by hadilq** [RatanShreshtha/DeepThought#52]
Hey, Thank you for your great work here.

I recently try to start to move away from Twitter to a more federated solution, and found https://github.com/mastodon/mastodon an elegant solution. Would you add it to the extra.social links? However, this solution can be launched on many different domains, so for starter I would suggest to add the main one in https://mastodon.social, something like mine, https://mastodon.social/@hadilq, Thanks!

**Comment by RatanShreshtha** [comment]
Thanks for the suggestion it is added
