### ISSUE TITLE
Feature request: KaTeX support

### ISSUE THREAD

**Issue by m4dh0rs3** [RatanShreshtha/DeepThought#7]
Themes like [even](https://github.com/getzola/even) or [pickles](https://github.com/lukehsiao/zola-pickles) support KaTeX with shortcodes.
This would be helpful, until [Zola #1073](https://github.com/getzola/zola/pull/1073) is closed.

**Comment by RatanShreshtha** [comment]
@m4dh0rs3 you can raise a PR for the feature.

**Comment by RatanShreshtha** [comment]
This feature is available now.
